name: Flyway Migration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Run migrations
        uses: docker://flyway/flyway:11.9.1
        with:
          args: >-
            -locations=filesystem:/github/workspace/migrations
            -url=jdbc:mysql://${{ secrets.DB_HOST }}/${{ secrets.DB_NAME }}?allowPublicKeyRetrieval=true&useSSL=false
            -user=${{ secrets.DB_USERNAME }}
            -password=${{ secrets.DB_PASSWORD }}
            -baselineOnMigrate=true
            migrate
